export const VENUE_TYPES = [
  'Independent Living',
  'Assisted Living',
  'Skilled Nursing',
  'Memory',
  'Nursing',
  'Rehabilitation',
  'Senior Center',
  'Private individual/Family',
  'School',
  'Restaurant',
  'Bar/Pub',
  'Club',
  'Event Arena',
  'Hotel',
];

export const ENTERTAINER_SKILLS_TYPES = [
  'Vocals',
  'Piano/Keyboard',
  'Guitar',
  'Violin',
  'Cello',
  'Accordion',
  'Harp',
  'Impersonator',
  'DJ/Karaoke',
  'Lecture',
  'Dance',
  'Comedy',
  'Magic',
];
